-- Character select screen lines
STRINGS.CHARACTER_TITLES.wagstaff = "The Cryptic Founder"
STRINGS.CHARACTER_NAMES.wagstaff = "Wagstaff"
STRINGS.CHARACTER_DESCRIPTIONS.wagstaff = "*A great inventor\n*Nearsighted\n*Delicate Stomach"
STRINGS.CHARACTER_QUOTES.wagstaff = "\"Eureka! My destiny awaits!\""
STRINGS.CHARACTER_SURVIVABILITY.wagstaff = "Slim"

-- Speech file
STRINGS.CHARACTERS.WAGSTAFF = require("speech_wagstaff")

-- Character's name in-game
STRINGS.NAMES.WAGSTAFF = "Wagstaff"
STRINGS.SKIN_NAMES.wagstaff_none = "Wagstaff"
-- Recipe Descriptions
STRINGS.NAMES.WAGGOGGLES_NORMAL_HAT = "Spectoggles"
STRINGS.RECIPE_DESC.WAGGOGGLES_NORMAL_HAT = "Basic super goggles. Reveal hidden danger"
STRINGS.NAMES.WAGGOGGLES_HEAT_HAT = "Infroggles"
STRINGS.RECIPE_DESC.WAGGOGGLES_HEAT_HAT = "Is everything hot or not"
STRINGS.NAMES.WAGGOGGLES_ARMOR_HAT = "Visor"
STRINGS.RECIPE_DESC.WAGGOGGLES_ARMOR_HAT = "Armored lenses"
STRINGS.NAMES.WAGGOGGLES_SHOOT_HAT = "Fryfocals"
STRINGS.RECIPE_DESC.WAGGOGGLES_SHOOT_HAT = "Static boom focusing apparatus"
STRINGS.RECIPE_DESC.WAG_TELEBRELLA = "A revolutionary walker"
STRINGS.RECIPE_DESC.WAG_TELIPAD = "A revolutionary teleporter"
STRINGS.RECIPE_DESC.WAG_THUMPER = "A revolutionary harvester"
STRINGS.NAMES.WAG_TELEBRELLA = "Telebrella"
STRINGS.NAMES.WAG_TELIPAD = "Telipad"
STRINGS.NAMES.WAG_THUMPER = "Thumper"

---------[[Wendy]]-----------
STRINGS.CHARACTERS.WENDY.DESCRIBE.WAGSTAFFNORMALGOGGLES = "Useless. Just like life."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WAGSTAFFHEATGOGGLES = "A pointless thing to put on my head."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WAGSTAFFARMORGOGGLES = "Everything comes at a price."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "The world looks like the photographs of Abigail I have."
STRINGS.CHARACTERS.WENDY.DESCRIBE.THUMPER = "Cold-hearted metallic destruction."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TELIPAD = "It can retreive me from the aether."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TELEBRELLA = "Momentarily relieves my weariness."

STRINGS.CHARACTERS.WENDY.DESCRIBE_NEARSIGHTED = "This is what the world looks like when I'm crying."

STRINGS.CHARACTERS.WENDY.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "This is what the world looks like when I'm crying."
STRINGS.CHARACTERS.WENDY.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "This is what the world looks like when I'm crying."
STRINGS.CHARACTERS.WENDY.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "This is what the world looks like when I'm crying."
STRINGS.CHARACTERS.WENDY.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "This is what the world looks like when I'm crying."
---------[[WX-78]]-----------
STRINGS.CHARACTERS.WX78.DESCRIBE.WAGSTAFFNORMALGOGGLES = "IT REQUIRES A SOFTWARE UPDATE"
STRINGS.CHARACTERS.WX78.DESCRIBE.WAGSTAFFHEATGOGGLES = "THIS OCULAR ENHANCEMENT MODULE IS OUTDATED"
STRINGS.CHARACTERS.WX78.DESCRIBE.WAGSTAFFARMORGOGGLES = "HEAD PROTECTION AT THE EXPENSE OF VISUAL PERFORMANCE"
STRINGS.CHARACTERS.WX78.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "NONFUNCTIONING. THIS MUST BE WHAT THE FLESHSACKS CALL \"GRIEF\""
STRINGS.CHARACTERS.WX78.DESCRIBE.THUMPER = "FINALLY SOMETHING THAT UNDERSTANDS ME"
STRINGS.CHARACTERS.WX78.DESCRIBE.TELIPAD = "CARRIAGE RETURN FOR A TELEPORTATION UNIT"
STRINGS.CHARACTERS.WX78.DESCRIBE.TELEBRELLA = "I AM NOT FOOLED BY ITS UMBRELLA IMITATION"

STRINGS.CHARACTERS.WX78.DESCRIBE_NEARSIGHTED = "MY EYE UNITS ARE VASTLY SUPERIOR TO THIS TECHNOLOGY"

STRINGS.CHARACTERS.WX78.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "MY EYE UNITS ARE VASTLY SUPERIOR TO THIS TECHNOLOGY"
STRINGS.CHARACTERS.WX78.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "MY EYE UNITS ARE VASTLY SUPERIOR TO THIS TECHNOLOGY"
STRINGS.CHARACTERS.WX78.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "MY EYE UNITS ARE VASTLY SUPERIOR TO THIS TECHNOLOGY"
STRINGS.CHARACTERS.WX78.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "MY EYE UNITS ARE VASTLY SUPERIOR TO THIS TECHNOLOGY"
---------[[Wickerbottom]]-----------
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WAGSTAFFNORMALGOGGLES = "I'm afraid they're not my prescription"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WAGSTAFFHEATGOGGLES = "Ridiculous."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WAGSTAFFARMORGOGGLES = "Head protection at the expense of periphery vision."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "I do like this particular shade of sepia."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.THUMPER = "I'm not familiar with this type of bird."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TELIPAD = "A teleportation receptical."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TELEBRELLA = "Not as good at rain protection as it is at teleportation."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE_NEARSIGHTED = "Have I lost my glasses again?"

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Have I lost my glasses again?"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Have I lost my glasses again?"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Have I lost my glasses again?"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Have I lost my glasses again?"
---------[[Woodie]]-----------
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WAGSTAFFNORMALGOGGLES = "What's the point of this, eh?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WAGSTAFFHEATGOGGLES = "Doesn't work."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WAGSTAFFARMORGOGGLES = "Not really that great for seeing."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "Don't think it's working."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.THUMPER = "I don't care if it's not a real bird, I still don't like it."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TELIPAD = "It works with the umbrella thing somehow."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TELEBRELLA = "This'll save some time."

STRINGS.CHARACTERS.WOODIE.DESCRIBE_NEARSIGHTED = "Nope. Don't think these work."

STRINGS.CHARACTERS.WOODIE.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Nope. Don't think these work."
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Nope. Don't think these work."
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Nope. Don't think these work."
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Nope. Don't think these work."
---------[[Maxwell]]-----------
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAGSTAFFNORMALGOGGLES = "I hardly see the need for these."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAGSTAFFHEATGOGGLES = "What kind of ridiculous person made these?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAGSTAFFARMORGOGGLES = "You're going to need that kind of armor if you can't see where you're going."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "If they worked, I might consider wearing these."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.THUMPER = "Does all my hard work for me."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TELIPAD = "I'm the rabbit and this is the hat."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TELEBRELLA = "It's like walking without the exertion."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE_NEARSIGHTED = "Causes blindness. How useful."

STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Causes blindness. How useful."
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Causes blindness. How useful."
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Causes blindness. How useful."
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Causes blindness. How useful."
---------[[Wigfrid]]-----------
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WAGSTAFFNORMALGOGGLES = "It mocks me with its pointlessness!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WAGSTAFFHEATGOGGLES = "One of Loki's tricks."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WAGSTAFFARMORGOGGLES = "A helm of bleary sight."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "It is of no use to me."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.THUMPER = "This metal bird has the force of Thor's hammer!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TELIPAD = "Returns me from another realm."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TELEBRELLA = "Aids me in my battle against walking!"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE_NEARSIGHTED = "It does battle with my eyes!"

STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "It does battle with my eyes!"
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "It does battle with my eyes!"
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "It does battle with my eyes!"
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "It does battle with my eyes!"
---------[[Webber]]-----------
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WAGSTAFFNORMALGOGGLES = "Haha! It makes us see all funny."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WAGSTAFFHEATGOGGLES = "Is this what a frog sees?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WAGSTAFFARMORGOGGLES = "It sounds all echo-ey in there."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "We can pretend they work. Pew! Pew!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.THUMPER = "Woah! That makes a big boom!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TELIPAD = "It's a teleportation pad. But it needs an umbrella thing to work."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TELEBRELLA = "A zoomy umbrella!"

STRINGS.CHARACTERS.WEBBER.DESCRIBE_NEARSIGHTED = "Woah! Everything's all wobbly!"

STRINGS.CHARACTERS.WEBBER.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Woah! Everything's all wobbly!"
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Woah! Everything's all wobbly!"
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Woah! Everything's all wobbly!"
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Woah! Everything's all wobbly!"
---------[[Warly]]-----------
STRINGS.CHARACTERS.WARLY.DESCRIBE.WAGSTAFFNORMALGOGGLES = "Can't see the point in these."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WAGSTAFFHEATGOGGLES = "If they worked, they'd be great for checking meat temperature."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WAGSTAFFARMORGOGGLES = "Perfect for running around blindly on a battlefield."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "Are those potatoes?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.THUMPER = "It's like a meat tenderizer for the ground."
STRINGS.CHARACTERS.WARLY.DESCRIBE.TELIPAD = "A lot better than the Paris Metro."
STRINGS.CHARACTERS.WARLY.DESCRIBE.TELEBRELLA = "I hope it doesn't cook me when I use it."

STRINGS.CHARACTERS.WARLY.DESCRIBE_NEARSIGHTED = "It's like looking through pea soup!"

STRINGS.CHARACTERS.WARLY.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "It's like looking through pea soup!"
STRINGS.CHARACTERS.WARLY.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "It's like looking through pea soup!"
STRINGS.CHARACTERS.WARLY.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "It's like looking through pea soup!"
STRINGS.CHARACTERS.WARLY.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "It's like looking through pea soup!"
---------[[Wormwood]]-----------
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WAGSTAFFNORMALGOGGLES = "Hehe. Funny eyes"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WAGSTAFFHEATGOGGLES = "Ribbit? No"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WAGSTAFFARMORGOGGLES = "Clink eye thing"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "Can't use"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.THUMPER = "Thump! Thump!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TELIPAD = "Not rain taker"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TELEBRELLA = "Returny place"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE_NEARSIGHTED = "Everything's air soupy!"

STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Everything's air soupy!"
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Everything's air soupy!"
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Everything's air soupy!"
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Everything's air soupy!"
---------[[Winona]]-----------
STRINGS.CHARACTERS.WINONA.DESCRIBE.WAGSTAFFNORMALGOGGLES = "These goggles are not for me."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WAGSTAFFHEATGOGGLES = "Shoot! I can't get these to work."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WAGSTAFFARMORGOGGLES = "Helps me bump into things and not get hurt."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "It has to work, I just don't know how."
STRINGS.CHARACTERS.WINONA.DESCRIBE.THUMPER = "Neat machine!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TELIPAD = "Such excellent machinery!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TELEBRELLA = "Takes walking out of the equation."

STRINGS.CHARACTERS.WINONA.DESCRIBE_NEARSIGHTED = "I can't see anything with these things on."

STRINGS.CHARACTERS.WINONA.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Wow! I've gone blind!"
STRINGS.CHARACTERS.WINONA.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Wow! I've gone blind!"
STRINGS.CHARACTERS.WINONA.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Wow! I've gone blind!"
STRINGS.CHARACTERS.WINONA.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Wow! I've gone blind!"
---------[[Wortox]]-----------
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WAGSTAFFNORMALGOGGLES = "Goggles for eyes, but I see just fine."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WAGSTAFFHEATGOGGLES = "Hopper goggles, but hop they do not."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WAGSTAFFARMORGOGGLES = "Big helmet for mortal's head."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "Hyuyu, how strange."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.THUMPER = "It goes: thump, thump, thump and leaves no stump."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TELIPAD = "Peew-woosh pad."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TELEBRELLA = "Peew-woosh umbrella for quick trip."

STRINGS.CHARACTERS.WORTOX.DESCRIBE_NEARSIGHTED = "Hyuyu, playing hide n' seek?"

STRINGS.CHARACTERS.WORTOX.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Hyuyu, playing hide n' seek?"
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Hyuyu, playing hide n' seek?"
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Hyuyu, playing hide n' seek?"
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Hyuyu, playing hide n' seek?"

---------[[Wurt]]-----------
STRINGS.CHARACTERS.WURT.DESCRIBE.WAGSTAFFNORMALGOGGLES = "Flort. Weird hat."
STRINGS.CHARACTERS.WURT.DESCRIBE.WAGSTAFFHEATGOGGLES = "Is frog friend!"
STRINGS.CHARACTERS.WURT.DESCRIBE.WAGSTAFFARMORGOGGLES = "I cannot see!"
STRINGS.CHARACTERS.WURT.DESCRIBE.WAGSTAFFSHOOTGOGGLES = "Funny hat goes pew-pew."
STRINGS.CHARACTERS.WURT.DESCRIBE.THUMPER = "Smash everything!"
STRINGS.CHARACTERS.WURT.DESCRIBE.TELIPAD = "Shiny carpet."
STRINGS.CHARACTERS.WURT.DESCRIBE.TELEBRELLA = "Umbrella can take me places."

STRINGS.CHARACTERS.WURT.DESCRIBE_NEARSIGHTED = "Florp! My eyes hurt!"

STRINGS.CHARACTERS.WURT.ANNOUNCE_PUTONGOGGLES_GOGGLESNORMALHAT = "Florp! My eyes hurt!"
STRINGS.CHARACTERS.WURT.ANNOUNCE_PUTONGOGGLES_GOGGLESHEATHAT = "Glurp! Froggy made my eyes hurt!"
STRINGS.CHARACTERS.WURT.ANNOUNCE_PUTONGOGGLES_GOGGLESARMORHAT = "Florp! My eyes hurt!"
STRINGS.CHARACTERS.WURT.ANNOUNCE_PUTONGOGGLES_GOGGLESSHOOTHAT = "Florp! My eyes hurt!"